print("***********************************")
print("******** TorToey Fruit Shop ********")
print("***********************************")
print("Item------------------Price")
print("Apple", 3, 30,"THB = ", 3*30,"THB")
print("Orage", 5, 50,"THB = ", 5*50,"THB")
print("Coconut",10 ,150,"THB =",10*150, "THB")
print("***********************************")
print("Total = ",(3*30)+(5*50)+(10*150),"THB")
print("*********** THANK YOU *************")