name = input("First Name : ")
lastname = input("Last Name : ")
Fnumber = input ("Select First Number : ")
Lnumber = input ("Select Last Number : ")
Total = int(Fnumber) + int(Lnumber)
print("Hello ",name,lastname)
print("Total First No. + Last No. = ",Total)
